apiVersion: v1
kind: Service
metadata:
  name: zookeeper
spec:
  selector:
    app: zookeeper
  type: {{ .Values.zookeeper.service.type }}
  ports:
    - protocol: TCP
      port: {{ .Values.zookeeper.service.port }}
      targetPort: {{ .Values.zookeeper.service.port }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.kafka.service.name  | default "kafka" }}
spec:
  selector:
    app: kafka
  type: {{ .Values.kafka.service.type }}
  ports:
    - protocol: TCP
      port: {{ .Values.kafka.service.port }}
      targetPort: {{ .Values.kafka.service.port }}
      nodePort: {{ .Values.kafka.service.nodePort | default 30092 }}

--- 
apiVersion: v1
kind: Service
metadata:
  name: producer
spec:
  selector:
    app: producer
  type: {{ .Values.producer.service.type }}
  ports:
    - protocol: TCP
      port: {{ .Values.producer.service.port }}
      targetPort: {{ .Values.producer.service.port }}
      nodePort: {{ .Values.producer.service.nodePort | default 30080 }}

--- 
apiVersion: v1
kind: Service
metadata:
  name: consumer
spec:
  selector:
    app: consumer
  type: {{ .Values.consumer.service.type }}
  ports:
    - protocol: TCP
      port: {{ .Values.consumer.service.port }}
      targetPort: {{ .Values.consumer.service.port }}
      nodePort: {{ .Values.consumer.service.nodePort | default 30081 }}

