# Default values for kaka-tutorial.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# This will set the replicaset count more information can be found here: https://kubernetes.io/docs/concepts/workloads/controllers/replicaset/
replicaCount: 1

# This sets the container image more information can be found here: https://kubernetes.io/docs/concepts/containers/images/
image:
  repository: kafka-tutorial
  # This sets the pull policy for images.
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: latest

service: 
  host: "kafka-tutorial.local"
  port: 8080
  type: NodePort

ingress: 
  enables: true
  host: "kafka-tutorial.local"
  path: /
  pathType: Prefix
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /

zookeeper:
  enabled: true
  image: confluentinc/cp-zookeeper:latest
  imagePullPolicy: Never
  environment:
    - name: ZOOKEEPER_CLIENT_PORT
      value: "2181"
  service:
    type: ClusterIP
    port: 2181

kafka:
  enabled: true
  image: confluentinc/cp-kafka:latest
  imagePullPolicy: Never
  environment:
    - name: KAFKA_LISTENERS
      value: "PLAINTEXT://0.0.0.0:9092"
    - name: KAFKA_ADVERTISED_LISTENERS 
      value: "PLAINTEXT://kafka:9092"
    - name: KAFKA_ZOOKEEPER_CONNECT
      value: "zookeeper:2181"
    - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
      value: "PLAINTEXT:PLAINTEXT"
    - name: KAFKA_INTER_BROKER_LISTENER_NAME
      value: "PLAINTEXT"
    - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
      value: "1"
    - name : KAFKA_BROKER_ID
      value: "1"
  service:
    type: NodePort
    port: 9092
    nodePort: 30092


producer:
  enabled: true
  image: producer:latest
  imagePullPolicy: Never
  service:
    type: NodePort
    port: 8080
    nodePort: 30080


consumer:
  enabled: true
  image: consumer:latest
  imagePullPolicy: Never
  service:
    type: NodePort
    port: 8081
    nodePort: 30081