# Default values for kaka-tutorial.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# This will set the replicaset count more information can be found here: https://kubernetes.io/docs/concepts/workloads/controllers/replicaset/
replicaCount: 1

resources:
  limits:
    cpu: 1.0
    memory: 512Mi
  requests:
    cpu: 1.0
    memory: 512Mi


ingress: 
  enables: true
  host: "kafka-tutorial.local"
  path: /
  pathType: Prefix
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /

zookeeper:
  enabled: true
  image: confluentinc/cp-zookeeper:latest
  imagePullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 2181
  environment:
    - name: ZOOKEEPER_CLIENT_PORT
      value: "2181"


kafka:
  enabled: true
  image: confluentinc/cp-kafka:latest
  imagePullPolicy: IfNotPresent
  service:
    name: kafkanew
    type: NodePort
    port: 9092
    nodePort: 30092
  environment:
    - name: KAFKA_LISTENERS
      value: "PLAINTEXT://0.0.0.0:9092"
    - name: KAFKA_ADVERTISED_LISTENERS 
      value: "PLAINTEXT://kafkanew:9092"
    - name: KAFKA_ZOOKEEPER_CONNECT
      value: "zookeeper:2181"
    - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
      value: "PLAINTEXT:PLAINTEXT"
    - name: KAFKA_INTER_BROKER_LISTENER_NAME
      value: "PLAINTEXT"
    - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
      value: "1"
    - name : KAFKA_BROKER_ID
      value: "1"


producer:
  enabled: true
  image: 
    repository: "docker.sendgrid.net/sendgrid/kafka-tutorial/producer"
    tag: "latest"
    pullPolicy: "IfNotPresent"
  environment:
    - name: KAFKA_BROKER
      value: "kafkanew:9092"
    - name: KAFKA_TOPIC
      value: "TEST_TOPIC"
  service:
    type: NodePort
    port: 8080
    nodePort: 30080


consumer:
  enabled: true
  image: 
    repository: "docker.sendgrid.net/sendgrid/kafka-tutorial/consumer"
    tag: "latest"
    pullPolicy: "IfNotPresent"
  environment:
    - name: KAFKA_BROKER
      value: "kafkanew:9092"
    - name: KAFKA_TOPIC
      value: "TEST_TOPIC"
  service:
    type: NodePort
    port: 8081
    nodePort: 30081


# service: 
#   host: "kafka-tutorial.local"
#   port: 8080
#   type: NodePort
